[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions_ota.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBUILD_TYPE_NORMAL
    -DCONFIG_BTDM_CONTROLLER_BAUD_RATE_4M=1
    -Itools/sdk/esp32/include

monitor_filters =
    esp32_exception_decoder

lib_deps =

[env:esp32dev_release]
extends = env:esp32dev
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBUILD_TYPE_RELEASE
    -Os
